### ISSUE TITLE
Integration with sub.rehab

### ISSUE THREAD

**Issue by theoware** [induna-crewneck/Reddit-Lemmy-Migrator#1]
I think the integration with sub.rehab, a website that lists lemmy alternatives for subreddits, could help finding communities which have different names than on Reddit.

**Comment by induna-crewneck** [comment]
While this sounds like a good idea, it is not something I am planning to do. Someone else is very welcome to fork the repo and implement this or contact me with their implementation and I can add it to this repo

**Comment by samuk** [comment]
Would https://pyscript.net/ help with this?

**Comment by induna-crewneck** [comment]
Implemented sub.rehab in v1.5
