### ISSUE TITLE
Cannot login to lemmy

### ISSUE THREAD

**Issue by ctpforr** [induna-crewneck/Reddit-Lemmy-Migrator#10]
The lemmy password field does not have an id, so the password gets sent to the hide/show password button instead.

Sending login + TAB + password + ENTER all in one go seems to work for me.   

`driver.find_element("id", "login-email-or-username").send_keys(lemmuname + Keys.TAB + lemmpass + Keys.ENTER)`

**Comment by induna-crewneck** [comment]
Yeah i believe this is a change in the lemmy login page that has been made since I made this. I'm working on an update and this fix is implemented. Not exactly how you did it but I fixed the locator for the password field

**Comment by induna-crewneck** [comment]
Should be fixed in 1.4 (live now)
