### ISSUE TITLE
Can't type in password

### ISSUE THREAD

**Issue by HamsterHam88** [induna-crewneck/Reddit-Lemmy-Migrator#11]
I can type in my username; however, when trying to type in my password, it doesn't let me. Nothing shows up. Am I doing something wrong?

**Comment by HamsterHam88** [comment]
2fa issue turned it off, and it worked.

**Comment by induna-crewneck** [comment]
Since v1.4 your password won't be displayed when entering to improve privacy. I might implement stars showing when entering the password in the future but for now this is how it is.
