### ISSUE TITLE
Doc should mention, that you need chrome-browser aswell

### ISSUE THREAD

**Issue by Heiss** [induna-crewneck/Reddit-Lemmy-Migrator#12]
Hey,

i installed your nice tool via wsl2 on windows. As i read, that i should install chromedriver i need to install chrome aswell. So i follow [this](https://www.gregbrisebois.com/posts/chromedriver-in-wsl2/) guide to get the browser up and your tool can connect to it.

You have to start a XServer on the windows side and disable the Access control. After the server starts, you can run the migrator.

I know, this is only needed for headless consoles, but maybe there are some other noobs out there, which wants to use your tool as well. :)

All other stuff goes as expected. Nice work.

Bye.

**Comment by induna-crewneck** [comment]
Added to the Readme, thanks
