### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by HamsterHam88** [induna-crewneck/Reddit-Lemmy-Migrator#13]
So I got the script to work and it finds all my subreddits I am in but the migration stops after a few - https://imgur.com/wAhxfIb

Am I doing something wrong here? Thanks for the help.

**Comment by induna-crewneck** [comment]
That is weird. Can you run it with debug enabled and see it you can get any more insight?

**Comment by HamsterHam88** [comment]
I get a rate limit sometimes, but it searches for the community on Lemmy but doesn't subscribe to it. Example:

Blink182@blink-182lemmy.world
https://lemmy.world/c/blink182

Also some are not found when they should be:

Darts not found on Lemmy.
https://lemmy.world/c/darts

**Comment by induna-crewneck** [comment]
Made some changes to the behaviour and error handling when joining communites. Please download v1.5, run with debug and let me know if the issue persists

**Comment by HamsterHam88** [comment]
Sorry, I didn't reply earlier. It works now for me. Thank you!!!
