### ISSUE TITLE
Error 2 should provide more information

### ISSUE THREAD

**Issue by sigma67** [induna-crewneck/Reddit-Lemmy-Migrator#4]
Hey, thanks for this great script! Working pretty well for me.

However, at least half of the communities on lemmy are throwing error 2 for me.  It should at least provide some info from the exception so we can now what's happening?

**Comment by induna-crewneck** [comment]
At the top of the script is a DEBUG flag, which you can change to 'DEBUG = 1'. This will give you more info throughout

**Comment by sigma67** [comment]
It would be nice if we could provide this flag from the command line at least, without having to edit the file.

**Comment by induna-crewneck** [comment]
Added. Will update the repo soon

**Comment by induna-crewneck** [comment]
New update with this functionality is up (1.3)
