### ISSUE TITLE
https://kbin.social/m/AmoledBackgrounds@lemmy.world exists

### ISSUE THREAD

**Issue by samuk** [induna-crewneck/Reddit-Lemmy-Migrator#6]
In the documentation you say that https://kbin.social/m/AmoledBackgrounds@lemmy.world cannot be joined from Kbin. That doesn't seem to be the case. I am able to subscribe to it from Kbin.

Do you have another example that illustrates this issue

**Comment by induna-crewneck** [comment]
If you run the kbin script with debug enabled you're might see an error pop up some times telling you it found a community on lemmy.world but can't access it through kbin. Those would be other examples.
